{
 "title": "Powerlink Box Dashboard",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "deviceId", "label": "Device ID", "query": { "query": "SHOW MEASUREMENTS" } }
  ]
 },
 "panels": [
  { "title": "Device State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "humitidy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ARD Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "ardVoltage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ARD Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "ardCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "query": "SELECT last(\"response_message_fan_1_fanSpeed\") FROM /^$deviceId$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "fan_1_fanSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ARD State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "ardState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Door State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "doorState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SPD State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "spdAlert" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lightning Strike Surges",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "spdSurge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heater State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "query": "SELECT last(\"response_message_heaterState\") FROM /^$deviceId$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "heaterState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Light State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "lightState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water Alarm",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "waterAlert" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fan State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "query": "SELECT last(\"response_message_fan_1_fanState\") FROM /^$deviceId$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "fan_1_fanState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DateTime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "dateTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "query": "SELECT last(\"response_message_runTime\") FROM /^$deviceId$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "runTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Flow Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"1_rxByte\",\"1_txByte\",\"1_rxPacket\",\"1_txPacket\",\"1_rxError\",\"1_txError\" \nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Port 1",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"1_rxByte\",\"1_txByte\",\"1_rxPacket\",\"1_txPacket\",\"1_rxError\",\"1_txError\" \nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Port 2",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"2_rxByte\",\"2_txByte\",\"2_rxPacket\",\"2_txPacket\",\"2_rxError\",\"2_txError\" \nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Port 3",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"3_rxByte\",\"3_txByte\",\"3_rxPacket\",\"3_txPacket\",\"3_rxError\",\"3_txError\" \nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Port 4",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"4_rxByte\",\"4_txByte\",\"4_rxPacket\",\"4_txPacket\",\"4_rxError\",\"4_txError\" \nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Port 5",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"5_rxByte\",\"5_txByte\",\"5_rxPacket\",\"5_txPacket\",\"5_rxError\",\"5_txError\" \nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Port 6",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"6_rxByte\",\"6_txByte\",\"6_rxPacket\",\"6_txPacket\",\"6_rxError\",\"6_txError\" \nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Port 7",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"7_rxByte\",\"7_txByte\",\"7_rxPacket\",\"7_txPacket\",\"7_rxError\",\"7_txError\" \nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Port 8",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"8_rxByte\",\"8_txByte\",\"8_rxPacket\",\"8_txPacket\",\"8_rxError\",\"8_txError\" \nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  }
 ]
}