{
 "title": "Powerlink Box Dashboard",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "deviceId", "label": "Device ID", "query": { "query": "SHOW MEASUREMENTS" } }
  ]
 },
 "panels": [
  { "title": "Device State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "response_message_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "response_message_humitidy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ARD Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "response_message_ardVoltage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ARD Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "response_message_ardCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "query": "SELECT last(\"response_message_fan_1_fanSpeed\") FROM /^$deviceId$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       {
        "params": [
         "response_message_fan_1_fanSpeed"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ARD State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "response_message_ardState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Door State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "response_message_doorState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SPD State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "response_message_spdAlert" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lightning Strike Surges",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "response_message_spdSurge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heater State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "query": "SELECT last(\"response_message_heaterState\") FROM /^$deviceId$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "response_message_heaterState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Light State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "response_message_lightState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water Alarm",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "response_message_waterAlert" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fan State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "query": "SELECT last(\"response_message_fan_1_fanState\") FROM /^$deviceId$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       {
        "params": [
         "response_message_fan_1_fanState"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Date Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "response_message_dateTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Run Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$deviceId$/",
     "query": "SELECT last(\"response_message_runTime\") FROM /^$deviceId$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "response_message_runTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Flow Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"response_1_rxByte\",\"response_1_txByte\",\"response_1_rxPacket\",\"response_1_txPacket\",\"response_1_rxError\",\"response_1_txError\" \nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Port 1",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"response_1_rxByte\",\"response_1_txByte\",\"response_1_rxPacket\",\"response_1_txPacket\",\"response_1_rxError\",\"response_1_txError\" \nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Port 2",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"response_2_rxByte\",\"response_2_txByte\",\"response_2_rxPacket\",\"response_2_txPacket\",\"response_2_rxError\",\"response_2_txError\" \nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Port 3",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"response_3_rxByte\",\"response_3_txByte\",\"response_3_rxPacket\",\"response_3_txPacket\",\"response_3_rxError\",\"response_3_txError\" \nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Port 4",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"response_4_rxByte\",\"response_4_txByte\",\"response_4_rxPacket\",\"response_4_txPacket\",\"response_4_rxError\",\"response_4_txError\" \nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Port 5",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"response_5_rxByte\",\"response_5_txByte\",\"response_5_rxPacket\",\"response_5_txPacket\",\"response_5_rxError\",\"response_5_txError\" \nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Port 6",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"response_6_rxByte\",\"response_6_txByte\",\"response_6_rxPacket\",\"response_6_txPacket\",\"response_6_rxError\",\"response_6_txError\" \nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Port 7",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"response_7_rxByte\",\"response_7_txByte\",\"response_7_rxPacket\",\"response_7_txPacket\",\"response_7_rxError\",\"response_7_txError\" \nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Port 8",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"response_8_rxByte\",\"response_8_txByte\",\"response_8_rxPacket\",\"response_8_txPacket\",\"response_8_rxError\",\"response_8_txError\" \nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs (For Troubleshooting and Testing, Not Needed in the Final Product)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "smartBox_ea3778399e77eeb4b1de318552b18d24",
     "query": "SELECT \"response_1_id\",\"response_1_rxByte\",\"response_1_txByte\",\"response_1_rxPacket\",\"response_1_txPacket\",\"response_1_rxError\",\"response_1_txError\",\"response_2_id\",\"response_2_rxByte\",\"response_2_txByte\",\"response_2_rxPacket\",\"response_2_txPacket\",\"response_2_rxError\",\"response_2_txError\",\"response_3_id\",\"response_3_rxByte\",\"response_3_txByte\",\"response_3_rxPacket\",\"response_3_txPacket\",\"response_3_rxError\",\"response_3_txError\",\"response_4_id\",\"response_4_rxByte\",\"response_4_txByte\",\"response_4_rxPacket\",\"response_4_txPacket\",\"response_4_rxError\",\"response_4_txError\"\nFROM /^$deviceId$/ \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "response_1_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "response_10_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "sys/device/smartBox_ea3778399e77eeb4b1de318552b18d24/command_reply/switch-port-statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "All command messages will appear here",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "measurement": "/^$deviceId$/",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}