apiVersion: 1

datasources:
  - name: InfluxDB_v2_InfluxQL
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      dbName: logs
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token root1234'
