services:
  emqx:
    image: emqx/emqx:5.8.5
    restart: always
    container_name: emqx_broker
    ports:
      - 1883:1883     # MQTT default port
      - 8083:8083     # WebSocket port
      - 8084:8084     # Secure WebSocket
      - 8883:8883     # MQTT over SSL/TLS
      - 18083:18083   # EMQX Dashboard (web UI)

    environment:
    - EMQX_DASHBOARD__DEFAULT_USERNAME=root
    - EMQX_DASHBOARD__DEFAULT_PASSWORD=root1234

  influxdb:
    image: influxdb:2.7.11
    container_name: influxdb_database
    ports:
      - "8086:8086"

    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME=root
    - DOCKER_INFLUXDB_INIT_PASSWORD=root1234
    - DOCKER_INFLUXDB_INIT_ORG=nms
    - DOCKER_INFLUXDB_INIT_BUCKET=logs
    - DOCKER_INFLUXDB_INIT_RETENTION=1w
    - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=root1234    

  grafana:
    build:
      context: grafana
      dockerfile: Dockerfile
    container_name: grafana_dashboard
    ports:
      - "3000:3000"

  python:
    build:
      context: python
      dockerfile: Dockerfile
    container_name: python_app
    depends_on:
      - emqx
      - influxdb
    stdin_open: true
    tty: true


